# Auto-update dependencies with dependabot
version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'update'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'update'
      include: 'scope'
